import type { PortfolioData } from '@app-types/portfolio'

export const mockPortfolioData: PortfolioData = {
  personalInfo: {
    name: 'John Doe',
    title: 'Senior Software Engineer',
    greeting: 'Hello, I am',
    profession: 'Software Engineer',
    resume_link: 'https://example.com/cv.pdf',
    location: { city: 'Paris', country: 'France' },
    bio: 'A passionate software engineer who loves building great products.',
    detailedBio: 'Detailed biography here.',
    avatar: { primary: '/images/avatar.jpg', alt: 'John Doe avatar' },
    languages: ['English', 'French'],
    birthday: '1990-01-15',
    availability: ['Full-time', 'Remote'],
  },
  contact: {
    email: 'john@example.com',
    phone: '+33 6 12 34 56 78',
    social: {
      github: { label: 'github.com/johndoe', url: 'https://github.com/johndoe' },
      linkedin: { label: 'linkedin.com/in/johndoe', url: 'https://linkedin.com/in/johndoe' },
      website: { label: 'johndoe.dev', url: 'https://johndoe.dev' },
      twitter: { label: '@johndoe', url: 'https://twitter.com/johndoe' },
      instagram: { label: '@johndoe', url: 'https://instagram.com/johndoe' },
      telegram: { label: '@johndoe', url: 'https://t.me/johndoe' },
    },
  },
  skills: {
    technical: [
      { name: 'React', level: 90, category: 'frontend' },
      { name: 'TypeScript', level: 85, category: 'language' },
      { name: 'Node.js', level: 80, category: 'backend' },
      { name: 'Jest', level: 75, category: 'testing' },
      { name: 'Docker', level: 70, category: 'tools' },
    ],
    categories: {
      frontend: ['React', 'Vue', 'CSS'],
      backend: ['Node.js', 'Express'],
      languages: ['TypeScript', 'JavaScript'],
      tools: ['Docker', 'Git'],
      testing: ['Jest', 'Vitest'],
      learning: ['Rust'],
    },
  },
  education: [
    {
      degree: 'Master of Computer Science',
      duration: '2012 - 2014',
      description: 'Studied algorithms, distributed systems, and software engineering.',
    },
  ],
  experience: [
    {
      company: 'Tech Corp',
      position: 'Senior Frontend Engineer',
      duration: '2020 - Present',
      description: 'Led development of large-scale React applications.',
      highlights: ['Built reusable UI components', 'Improved performance by 30%'],
    },
  ],
  services: [
    { id: 1, title: 'Web Development', description: 'Building modern web apps.' },
    { id: 2, title: 'Mobile Development', description: 'React Native apps.' },
  ],
  projects: [
    {
      id: 1,
      title: 'Portfolio Website',
      url: 'https://johndoe.dev',
      projectTypes: ['full-stack', 'frontend', 'backend'],
      excerpt: 'A modern portfolio built with React and TypeScript.',
      category: 'Web',
      tags: ['React', 'TypeScript', 'Vite'],
      shortDescription: 'A modern portfolio built with React and TypeScript.',
      highlights: ['Responsive design', 'Fast load times'],
      publishDate: '2024-01-01',
    },
    {
      id: 2,
      title: 'Open Source CLI Tool',
      projectTypes: ['misc'],
      excerpt: 'A command-line utility written in Node.js.',
      category: 'Tools',
      tags: ['Node.js', 'CLI'],
      shortDescription: 'A command-line utility written in Node.js.',
      highlights: ['Cross-platform', 'Easy to use'],
      publishDate: '2023-06-15',
    },
  ],
  blog: [
    {
      id: 1,
      title: 'I Ditched Axios for Ky And My Dependabot Finally Stopped Screaming',
      url: 'https://izsk.hashnode.dev/i-ditched-axios-for-ky-and-my-dependabot-finally-stopped-screaming',
      blogTypes: ['frontend', 'backend', 'architecture'],
      excerpt: 'A personal breakdown of Fetch, Axios, and why Ky quietly became my go-to HTTP client in React.',
      shortDescription:
        'A practical comparison of Fetch, Axios, and Ky through the lens of bundle weight, retries, timeouts, TypeScript ergonomics, and the security cost of unnecessary dependencies.',
      highlights: [
        'Compares Fetch, Axios, and Ky through real React and TanStack Query usage',
        'Breaks down Axios security incidents and supply-chain risk as a decision factor',
        'Explains why Ky became the default request layer for modern React projects',
      ],
      category: 'Frontend Architecture',
      tags: ['React', 'TypeScript', 'Ky', 'Axios', 'Fetch API', 'TanStack Query', 'Security'],
      publishDate: '2026-05-02',
    },
    {
      id: 2,
      title: 'Context vs Redux Toolkit vs Zustand: Picking the Right State Tool for the Job',
      url: 'https://izsk.hashnode.dev/context-vs-redux-toolkit-vs-zustand-picking-the-right-state-tool-for-the-job',
      blogTypes: ['frontend', 'state-management', 'architecture'],
      excerpt: "You don't need the most powerful state manager. You need the right one.",
      shortDescription:
        'A production-minded comparison of React Context, Redux Toolkit, and Zustand, focused on re-render behavior, boilerplate, team scaling, and the tradeoffs that matter months after launch.',
      highlights: [
        'Maps the strengths and weaknesses of Context, Redux Toolkit, and Zustand',
        'Explains the Context re-render trap and why selector-based stores feel better at scale',
        'Shows when scoped Zustand plus Context is the right hybrid pattern',
      ],
      category: 'State Management',
      tags: ['React', 'TypeScript', 'Zustand', 'Redux Toolkit', 'React Context', 'State Management'],
      publishDate: '2026-05-10',
    },
    {
      id: 3,
      title: "React Query vs SWR vs the `use` Hook: Why You're Fetching Data Wrong",
      url: 'https://izsk.hashnode.dev/react-query-vs-swr-vs-the-use-hook-why-you-re-fetching-data-wrong',
      blogTypes: ['frontend', 'architecture', 'state-management'],
      excerpt:
        "You already know how to fetch data. What you're missing is everything that happens after.",
      shortDescription:
        "A production-focused comparison of raw fetch, SWR, React 19's `use` hook, and TanStack Query, centered on caching, mutations, race conditions, and why client-side data fetching is really a state synchronization problem.",
      highlights: [
        'Explains where raw fetch and Axios break down once caching, deduplication, and stale data enter the picture',
        'Shows why the React 19 `use` hook is powerful in server components but limited as a client-side data fetching strategy',
        'Compares SWR and TanStack Query through mutations, optimistic updates, DevTools, infinite queries, and real production tradeoffs',
      ],
      category: 'Data Fetching',
      tags: [
        'React',
        'TypeScript',
        'React Query',
        'TanStack Query',
        'SWR',
        'React 19',
        'use Hook',
        'Suspense',
        'Data Fetching',
        'State Synchronization',
      ],
      publishDate: '2026-05-25',
    },
    {
      id: 4,
      title: "You're Probably Using React Memoization Wrong (And So Was I)",
      url: 'https://izsk.hashnode.dev/you-re-probably-using-react-memoization-wrong-and-so-was-i',
      blogTypes: ['frontend', 'architecture'],
      excerpt:
        'Memoization is a performance tool, not a coding habit. Most of the time, the simpler version is the better version.',
      shortDescription:
        'A practical guide to `useMemo`, `useCallback`, and `React.memo`, focused on when they solve real performance problems, when they add noise, and how React 19 changes the tradeoffs.',
      highlights: [
        'Explains when `useMemo`, `useCallback`, and `React.memo` actually save meaningful work',
        'Breaks down the reference equality traps that make manual memoization ineffective',
        'Shows how React 19, `useDeferredValue`, and `useTransition` shift the performance conversation beyond blanket memoization',
      ],
      category: 'Frontend Architecture',
      tags: [
        'React',
        'React 19',
        'useMemo',
        'useCallback',
        'React.memo',
        'Memoization',
        'Performance',
        'Profiler',
        'useDeferredValue',
        'useTransition',
      ],
      publishDate: '2026-05-31',
    },
  ],
}
