import type { PortfolioData } from '@app-types/portfolio'

export const mockPortfolioData: PortfolioData = {
  personalInfo: {
    name: 'John Doe',
    title: 'Senior Software Engineer',
    greeting: 'Hello, I am',
    profession: 'Software Engineer',
    resume_link: 'https://example.com/cv.pdf',
    location: { city: 'Paris', country: 'France' },
    bio: 'A passionate software engineer who loves building great products.',
    detailedBio: 'Detailed biography here.',
    avatar: { primary: '/images/avatar.jpg', alt: 'John Doe avatar' },
    languages: ['English', 'French'],
    birthday: '1990-01-15',
    availability: ['Full-time', 'Remote'],
  },
  contact: {
    email: 'john@example.com',
    phone: '+33 6 12 34 56 78',
    social: {
      github: { label: 'github.com/johndoe', url: 'https://github.com/johndoe' },
      linkedin: { label: 'linkedin.com/in/johndoe', url: 'https://linkedin.com/in/johndoe' },
      website: { label: 'johndoe.dev', url: 'https://johndoe.dev' },
      twitter: { label: '@johndoe', url: 'https://twitter.com/johndoe' },
      instagram: { label: '@johndoe', url: 'https://instagram.com/johndoe' },
      telegram: { label: '@johndoe', url: 'https://t.me/johndoe' },
    },
  },
  skills: {
    technical: [
      { name: 'React', level: 90, category: 'frontend' },
      { name: 'TypeScript', level: 85, category: 'language' },
      { name: 'Node.js', level: 80, category: 'backend' },
      { name: 'Jest', level: 75, category: 'testing' },
      { name: 'Docker', level: 70, category: 'tools' },
    ],
    categories: {
      frontend: ['React', 'Vue', 'CSS'],
      backend: ['Node.js', 'Express'],
      languages: ['TypeScript', 'JavaScript'],
      tools: ['Docker', 'Git'],
      testing: ['Jest', 'Vitest'],
      learning: ['Rust'],
    },
  },
  education: [
    {
      degree: 'Master of Computer Science',
      duration: '2012 - 2014',
      description: 'Studied algorithms, distributed systems, and software engineering.',
    },
  ],
  experience: [
    {
      company: 'Tech Corp',
      position: 'Senior Frontend Engineer',
      duration: '2020 - Present',
      description: 'Led development of large-scale React applications.',
      highlights: ['Built reusable UI components', 'Improved performance by 30%'],
    },
  ],
  services: [
    { id: 1, title: 'Web Development', description: 'Building modern web apps.' },
    { id: 2, title: 'Mobile Development', description: 'React Native apps.' },
  ],
  projects: [
    {
      id: 1,
      title: 'Portfolio Website',
      url: 'https://johndoe.dev',
      projectTypes: ['full-stack', 'frontend', 'backend'],
      excerpt: 'A modern portfolio built with React and TypeScript.',
      category: 'Web',
      tags: ['React', 'TypeScript', 'Vite'],
      shortDescription: 'A modern portfolio built with React and TypeScript.',
      highlights: ['Responsive design', 'Fast load times'],
      publishDate: '2024-01-01',
    },
    {
      id: 2,
      title: 'Open Source CLI Tool',
      projectTypes: ['misc'],
      excerpt: 'A command-line utility written in Node.js.',
      category: 'Tools',
      tags: ['Node.js', 'CLI'],
      shortDescription: 'A command-line utility written in Node.js.',
      highlights: ['Cross-platform', 'Easy to use'],
      publishDate: '2023-06-15',
    },
  ],
  blog: [
    {
      id: 1,
      title: 'I Ditched Axios for Ky And My Dependabot Finally Stopped Screaming',
      url: 'https://izsk.hashnode.dev/i-ditched-axios-for-ky-and-my-dependabot-finally-stopped-screaming',
      blogTypes: ['frontend', 'backend', 'architecture'],
      excerpt: 'A personal breakdown of Fetch, Axios, and why Ky quietly became my go-to HTTP client in React.',
      shortDescription:
        'A practical comparison of Fetch, Axios, and Ky through the lens of bundle weight, retries, timeouts, TypeScript ergonomics, and the security cost of unnecessary dependencies.',
      highlights: [
        'Compares Fetch, Axios, and Ky through real React and TanStack Query usage',
        'Breaks down Axios security incidents and supply-chain risk as a decision factor',
        'Explains why Ky became the default request layer for modern React projects',
      ],
      category: 'Frontend Architecture',
      tags: ['React', 'TypeScript', 'Ky', 'Axios', 'Fetch API', 'TanStack Query', 'Security'],
      publishDate: '2026-05-02',
    },
    {
      id: 2,
      title: 'Context vs Redux Toolkit vs Zustand: Picking the Right State Tool for the Job',
      url: 'https://izsk.hashnode.dev/context-vs-redux-toolkit-vs-zustand-picking-the-right-state-tool-for-the-job',
      blogTypes: ['frontend', 'state-management', 'architecture'],
      excerpt: "You don't need the most powerful state manager. You need the right one.",
      shortDescription:
        'A production-minded comparison of React Context, Redux Toolkit, and Zustand, focused on re-render behavior, boilerplate, team scaling, and the tradeoffs that matter months after launch.',
      highlights: [
        'Maps the strengths and weaknesses of Context, Redux Toolkit, and Zustand',
        'Explains the Context re-render trap and why selector-based stores feel better at scale',
        'Shows when scoped Zustand plus Context is the right hybrid pattern',
      ],
      category: 'State Management',
      tags: ['React', 'TypeScript', 'Zustand', 'Redux Toolkit', 'React Context', 'State Management'],
      publishDate: '2026-05-10',
    },
    {
      id: 3,
      title: "React Query vs SWR vs the `use` Hook: Why You're Fetching Data Wrong",
      url: 'https://izsk.hashnode.dev/react-query-vs-swr-vs-the-use-hook-why-you-re-fetching-data-wrong',
      blogTypes: ['frontend', 'architecture', 'state-management'],
      excerpt:
        "You already know how to fetch data. What you're missing is everything that happens after.",
      shortDescription:
        "A production-focused comparison of raw fetch, SWR, React 19's `use` hook, and TanStack Query, centered on caching, mutations, race conditions, and why client-side data fetching is really a state synchronization problem.",
      highlights: [
        'Explains where raw fetch and Axios break down once caching, deduplication, and stale data enter the picture',
        'Shows why the React 19 `use` hook is powerful in server components but limited as a client-side data fetching strategy',
        'Compares SWR and TanStack Query through mutations, optimistic updates, DevTools, infinite queries, and real production tradeoffs',
      ],
      category: 'Data Fetching',
      tags: [
        'React',
        'TypeScript',
        'React Query',
        'TanStack Query',
        'SWR',
        'React 19',
        'use Hook',
        'Suspense',
        'Data Fetching',
        'State Synchronization',
      ],
      publishDate: '2026-05-25',
    },
    {
      id: 4,
      title: "You're Probably Using React Memoization Wrong (And So Was I)",
      url: 'https://izsk.hashnode.dev/you-re-probably-using-react-memoization-wrong-and-so-was-i',
      blogTypes: ['frontend', 'architecture'],
      excerpt:
        'Memoization is a performance tool, not a coding habit. Most of the time, the simpler version is the better version.',
      shortDescription:
        'A practical guide to `useMemo`, `useCallback`, and `React.memo`, focused on when they solve real performance problems, when they add noise, and how React 19 changes the tradeoffs.',
      highlights: [
        'Explains when `useMemo`, `useCallback`, and `React.memo` actually save meaningful work',
        'Breaks down the reference equality traps that make manual memoization ineffective',
        'Shows how React 19, `useDeferredValue`, and `useTransition` shift the performance conversation beyond blanket memoization',
      ],
      category: 'Frontend Architecture',
      tags: [
        'React',
        'React 19',
        'useMemo',
        'useCallback',
        'React.memo',
        'Memoization',
        'Performance',
        'Profiler',
        'useDeferredValue',
        'useTransition',
      ],
      publishDate: '2026-05-31',
    },
    {
      id: 5,
      title: 'React Compound Components: The Pattern That Makes Component APIs Actually Good',
      url: 'https://izsk.hashnode.dev/react-compound-components-the-pattern-that-makes-component-apis-actually-good',
      blogTypes: ['frontend', 'architecture', 'state-management'],
      excerpt:
        'A long-form React architecture article on why prop-heavy components break down at scale and how compound components produce cleaner, more maintainable APIs.',
      shortDescription:
        'A practical deep dive into the compound components pattern in React, covering why monolithic prop-driven APIs become unmaintainable, how Context-based composition gives consumers layout control without losing shared state, and how to design the pattern correctly in TypeScript for real component libraries and design systems.',
      highlights: [
        'Builds Tabs and Accordion compound components from scratch with Context-based state sharing',
        'Explains controlled vs uncontrolled APIs, namespaced TypeScript sub-components, and why Context beats `React.Children.map` here',
        'Covers real-world usage, common mistakes, and lighter alternatives such as render props, config objects, and named slots',
      ],
      category: 'Frontend Architecture',
      tags: [
        'React',
        'TypeScript',
        'Compound Components',
        'Context API',
        'Component API Design',
        'Design Systems',
        'Radix UI',
        'Headless UI',
        'Ant Design',
        'Controlled Components',
        'Uncontrolled Components',
      ],
      publishDate: '2026-06-07',
    },
    {
      id: 6,
      title: 'React Virtualization: Fast Tables With Thousands of Rows',
      url: 'https://izsk.hashnode.dev/your-table-has-10-000-rows-your-browser-has-one-dom-let-s-talk-about-virtualization',
      blogTypes: ['frontend', 'architecture'],
      excerpt:
        'A practical, opinionated deep dive into React list and table virtualization focused on large datasets, real bottlenecks, and the tradeoffs behind adding windowing at all.',
      shortDescription:
        'This article treats virtualization as a DOM scaling problem first and a React implementation detail second. It starts with a DevTools-based workflow to confirm whether rendering cost is actually the bottleneck before reaching for a library, then walks through how windowing works under the hood, when it is the right call, when it is unnecessary, and how to implement it with TanStack Virtual, react-window, react-virtuoso, TanStack Table, and TanStack Query. It also covers variable row height strategies, infinite scroll, sticky headers, accessibility limitations, and the CSS and state-management mistakes that usually make virtualized tables feel fragile.',
      highlights: [
        'Explains virtualization from first principles: DOM recycling, scroll math, overscan, and why the browser usually fails before React does',
        'Shows when to use virtualization and when to skip it for simpler options such as pagination, server-side filtering, or append-only lists',
        'Includes practical implementations with TanStack Virtual, react-window, react-virtuoso, TanStack Table, and `useInfiniteQuery`',
        'Covers variable-height rows, sticky header setup, refetch scroll-loss issues, and other failure modes that appear in real tables',
        'Ends with the same rule as the rest of the series: measure first, then add complexity only when the evidence says you need it',
      ],
      category: 'Frontend Performance',
      tags: [
        'React',
        'TypeScript',
        'Virtualization',
        'TanStack Virtual',
        'react-window',
        'react-virtuoso',
        'TanStack Table',
        'TanStack Query',
        'Performance',
        'DOM',
        'DevTools',
        'Infinite Scroll',
      ],
      publishDate: '2026-06-14',
    },
    {
      id: 7,
      title: "Concurrent Rendering in React: What It Actually Is, And When It's Just Hiding a Problem",
      url: 'https://izsk.hashnode.dev/concurrent-rendering-in-react-what-it-actually-is-and-when-it-s-just-hiding-a-problem',
      blogTypes: ['frontend', 'architecture'],
      excerpt:
        "Concurrent rendering is not multi-threading. It's React's way of rescheduling render work so urgent updates stay responsive.",
      shortDescription:
        "A technical deep dive into React's concurrent rendering model, focused on what Fiber actually enables, how urgent and non-urgent updates shape the API surface, when `startTransition`, `useTransition`, and `useDeferredValue` genuinely help, and when they are just masking a slower underlying problem.",
      highlights: [
        'Explains why concurrent rendering stays single-threaded and what Fiber actually makes interruptible',
        'Breaks down `startTransition`, `useTransition`, and `useDeferredValue` through real UI cases and a clear decision table',
        'Shows how concurrent rendering and Suspense fit together in data-heavy flows such as product detail navigation',
        'Ends with a practical diagnosis framework so you measure the real bottleneck before reaching for any concurrent API',
      ],
      category: 'Frontend Performance',
      tags: [
        'React',
        'React 19',
        'Concurrent Rendering',
        'Fiber',
        'startTransition',
        'useTransition',
        'useDeferredValue',
        'Suspense',
        'Performance',
        'Scheduling',
      ],
      publishDate: '2026-06-21',
    },
    {
      id: 8,
      title: "React Reconciliation and Keys: What's Actually Happening When Your Component Re-Renders",
      url: 'https://izsk.hashnode.dev/react-reconciliation-and-keys-what-s-actually-happening-when-your-component-re-renders',
      blogTypes: ['frontend', 'architecture'],
      excerpt:
        'Keys do not magically fix list bugs. They tell React which child identity should survive the next diff.',
      shortDescription:
        'A deep dive into React reconciliation focused on how the diffing heuristic actually matches elements, when a component updates versus remounts, why unstable keys corrupt stateful lists, and how Fiber makes selective reuse possible.',
      highlights: [
        "Explains React's two core diffing rules: type changes tear down subtrees, and same-type siblings are matched by key",
        'Shows step by step why removing an item from a stateful list breaks under positional diffing and why index keys behave the same way',
        'Clarifies the exact difference between a re-render and a remount, including what state survives and what resets',
        'Connects reconciliation to Fiber internals, current versus work-in-progress trees, and practical DevTools debugging for unexpected remounts',
      ],
      category: 'Frontend Performance',
      tags: [
        'React',
        'React 19',
        'Reconciliation',
        'Keys',
        'Fiber',
        'Component Lifecycle',
        'State Preservation',
        'Remounting',
        'Profiler',
        'DevTools',
      ],
      publishDate: '2026-06-28',
    },
    {
      id: 9,
      title: 'JavaScript Loops: Stop Using map() for Everything',
      url: 'https://izsk.hashnode.dev/javascript-loops-stop-using-map-for-everything',
      blogTypes: ['frontend', 'architecture'],
      excerpt:
        "Most loop mistakes are not style choices. They're cases where the code is saying one thing and doing another.",
      shortDescription:
        'A practical guide to choosing the right JavaScript loop based on intent, control flow, return value, async behavior, and readability, with concrete reasons to use `for`, `while`, `for...of`, `forEach`, `map`, `filter`, `reduce`, `find`, `some`, `every`, and `flatMap`.',
      highlights: [
        'Separates imperative loops from functional array methods so the first decision is obvious',
        'Explains the real tradeoffs behind `for`, `for...of`, `forEach`, `map`, `filter`, and `reduce` instead of treating them as style preferences',
        'Calls out common production mistakes such as `forEach` with `async`/`await`, `map` for side effects, and `filter` where `some` or `find` should short-circuit',
      ],
      category: 'Frontend Architecture',
      tags: ['JavaScript', 'Frontend', 'WebDevelopment', 'Programming'],
      publishDate: '2026-07-19',
    },
    {
      id: 10,
      title: 'Debugging React Apps Like a Senior Dev',
      url: 'https://izsk.hashnode.dev/debugging-react-apps-like-a-senior-dev',
      blogTypes: ['frontend', 'architecture', 'state-management'],
      excerpt:
        'Senior debugging starts before the first console.log. The difference is whether you form a hypothesis before touching anything.',
      shortDescription:
        'A practical, opinionated guide to debugging React applications systematically instead of randomly. Built around a four-part bug taxonomy, it covers React DevTools, the Profiler, `useEffect` failure patterns, re-render diagnostics, state and network debugging, memory leaks, production observability, and a six-step checklist for forming and testing hypotheses.',
      highlights: [
        'Opens with a four-category bug taxonomy: wrong state, wrong render logic, wrong effect, or wrong external input',
        'Shows how to use React DevTools, the Profiler, why-did-you-render, and browser tooling to validate a debugging hypothesis fast',
        'Covers the highest-frequency React bug classes including unstable effect dependencies, stale closures, render storms, cache confusion, and memory leaks',
        'Includes practical production debugging guidance for source maps in Vite, Sentry with React error boundaries, feature flags, and structured console breadcrumbs',
      ],
      category: 'Frontend Debugging',
      tags: [
        'React',
        'React DevTools',
        'Profiler',
        'useEffect',
        'Debugging',
        'Zustand',
        'TanStack Query',
        'Sentry',
        'Vite',
        'Memory Leaks',
        'Chrome DevTools',
        'why-did-you-render',
      ],
      publishDate: '2026-07-26',
    },
    {
      id: 11,
      title: 'Web Performance Beyond Lighthouse: What Actually Moves the Needle',
      url: 'https://izsk.hashnode.dev/web-performance-beyond-lighthouse-what-actually-moves-the-needle',
      blogTypes: ['frontend', 'architecture'],
      excerpt:
        'A high Lighthouse score and a fast real-user experience are related, but they are not the same thing.',
      shortDescription:
        'A technical deep dive into modern web performance that separates lab scores from field reality, explains Core Web Vitals by mechanism, and focuses on the changes that materially improve what users actually feel across devices, networks, and full sessions.',
      highlights: [
        'Explains the difference between Lighthouse lab data and CrUX field data, including where each fits in a real performance workflow',
        'Breaks down LCP, CLS, and INP through root causes, DevTools diagnosis, and the browser mechanics behind each metric',
        'Covers practical fixes across bundles, images, fonts, third-party scripts, long tasks, and main-thread congestion',
        'Ends with a pragmatic stack: Lighthouse CI, web-vitals, CrUX, WebPageTest, and Sentry Performance, with guidance on when to add each one',
      ],
      category: 'Frontend Performance',
      tags: [
        'Web Performance',
        'Lighthouse',
        'Core Web Vitals',
        'CrUX',
        'INP',
        'LCP',
        'CLS',
        'WebPageTest',
        'DevTools',
        'Performance Budgets',
        'Sentry',
        'React',
      ],
      publishDate: '2026-08-03',
    },
  ],
}
